version: 2
updates:
  # Dependencies listed in go.mod
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      k8s.io: # Group k8s.io golang dependencies updates
          patterns:
            - "k8s.io/*"
    labels:
      - go
      - dependencies
      - ok-to-test
